version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/receipt-db?replicaSet=rs0

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: |
        echo 'try {
          rs.status()
        } catch (err) {
          rs.initiate({
            _id: "rs0",
            members: [{ _id: 0, host: "mongodb:27017" }]
          })
        }' | mongosh --quiet
      interval: 5s
      timeout: 30s
      start_period: 5s
      retries: 30