spring:
  application:
    name: receipt-processor-backend
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/receipt_db}
      database: receipt_db
      uuid-representation: standard
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://composed-swan-44.clerk.accounts.dev}

# Default springdoc configuration (will be overridden by profiles)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  packages-to-scan: com.fetch.receiptprocessor.controller
  paths-to-match: /receipts/**
